// ─── Atlas Autonomous AI — Type System ──────────────────────────────────────
// Level 5 Architecture: Fully autonomous multi-agent orchestration
//
// Core concept: "Cowork" — AI agents collaborate like a real team.
// Each agent has:  Role → Capabilities → Memory → Autonomy Level
//
// Pipeline: Command → Planner → Sub-Agents → Approval Gates → Execution → Learning
// ─────────────────────────────────────────────────────────────────────────────

// ─── Autonomous Command ─────────────────────────────────────────────────────

/** A high-level command from the user (could trigger multi-step autonomous flow) */
export interface AutonomousCommand {
  id: string;
  input: string;                    // Raw user input in any language
  sessionId: string;
  userId: string;
  createdAt: number;
  priority: "low" | "normal" | "high" | "critical";
}

/** The master plan generated by the Planner agent */
export interface MasterPlan {
  id: string;
  commandId: string;
  goal: string;                     // What we're trying to achieve
  reasoning: string;                // WHY this plan
  complexity: "trivial" | "simple" | "moderate" | "complex" | "epic";
  estimatedMs: number;
  phases: Phase[];
  requiresApproval: boolean;        // Does the whole plan need CEO approval?
  autonomyLevel: AutonomyLevel;
  status: PlanStatus;
  createdAt: number;
  completedAt?: number;
}

export type PlanStatus = "planning" | "awaiting_approval" | "executing" | "paused" | "completed" | "failed" | "cancelled";
export type AutonomyLevel = "full" | "supervised" | "approval_required" | "manual";

/** A phase in the master plan (sequential) */
export interface Phase {
  id: number;
  name: string;
  description: string;
  tasks: AgentTask[];
  status: PhaseStatus;
  gateType: "auto" | "approval" | "condition";
  gateCondition?: string;           // e.g., "content_quality > 0.8"
}

export type PhaseStatus = "pending" | "running" | "awaiting_gate" | "completed" | "failed" | "skipped";

// ─── Agent Tasks ────────────────────────────────────────────────────────────

/** A task assigned to a specific sub-agent */
export interface AgentTask {
  id: string;
  phaseId: number;
  agent: SubAgentType;
  action: string;                   // What to do
  description: string;              // Human-readable description
  input: Record<string, unknown>;   // Input data for the agent
  output?: Record<string, unknown>; // Result data after execution
  dependencies: string[];           // Task IDs that must complete first
  status: TaskStatus;
  priority: number;
  retries: number;
  maxRetries: number;
  error?: string;
  startedAt?: number;
  completedAt?: number;
  durationMs?: number;
}

export type TaskStatus = "pending" | "queued" | "running" | "awaiting_approval" | "completed" | "failed" | "cancelled" | "skipped";

/** Sub-agent types — each specializes in a domain */
export type SubAgentType =
  | "planner"           // Decomposes commands into plans
  | "researcher"        // Fetches and analyzes data from DB
  | "writer"            // Generates text content (posts, emails, reports)
  | "designer"          // Generates image prompts / visual content descriptions
  | "video_producer"    // Generates video scripts / storyboards
  | "social_manager"    // Manages social media scheduling & posting
  | "analyst"           // Deep data analysis, trends, predictions
  | "operator"          // Executes DB mutations (CRUD operations)
  | "notifier"          // Sends notifications, emails, alerts
  | "quality_checker"   // Reviews output quality before publishing
  | "scheduler"         // Manages timed/recurring tasks
  | "monitor"           // Proactive monitoring & anomaly detection
  ;

// ─── Content Pipeline ───────────────────────────────────────────────────────

/** Content generated by the AI for any channel */
export interface GeneratedContent {
  id: string;
  type: ContentType;
  title: string;
  body: string;                     // Main content (text, script, prompt)
  metadata: ContentMetadata;
  quality: QualityScore;
  status: ContentStatus;
  targetChannel?: SocialChannel;
  targetCustomerId?: string;
  createdAt: number;
  approvedAt?: number;
  publishedAt?: number;
}

export type ContentType = "social_post" | "email" | "report" | "ad_copy" | "video_script" | "image_prompt" | "blog_post" | "notification";
export type ContentStatus = "draft" | "review" | "approved" | "published" | "rejected" | "archived";
export type SocialChannel = "instagram" | "facebook" | "twitter" | "linkedin" | "tiktok" | "youtube";

export interface ContentMetadata {
  language: string;
  tone: string;
  targetAudience?: string;
  hashtags?: string[];
  imagePrompt?: string;
  videoScript?: string;
  scheduledAt?: number;
  customerId?: string;              // Which customer this is for
  customerName?: string;
}

export interface QualityScore {
  overall: number;                  // 0-100
  dimensions: {
    relevance: number;
    clarity: number;
    engagement: number;
    brandAlign: number;
  };
  issues: string[];
  suggestions: string[];
}

// ─── Approval System ────────────────────────────────────────────────────────

export interface ApprovalRequest {
  id: string;
  type: ApprovalType;
  title: string;
  description: string;
  data: Record<string, unknown>;    // The thing to approve
  preview?: string;                 // Human-readable preview
  requestedBy: SubAgentType;
  requestedAt: number;
  urgency: "low" | "normal" | "high" | "critical";
  status: "pending" | "approved" | "rejected" | "expired";
  decidedBy?: string;
  decidedAt?: number;
  reason?: string;
  expiresAt?: number;
  planId?: string;
  taskId?: string;
}

export type ApprovalType =
  | "content_publish"     // Publish content to social media
  | "data_mutation"       // Modify database records
  | "send_notification"   // Send email/notification to customer
  | "workflow_execute"    // Execute a multi-step workflow
  | "budget_spend"        // Spend money (ad campaigns)
  | "plan_approval"       // Approve a master plan
  ;

// ─── Proactive Intelligence ─────────────────────────────────────────────────

export interface ProactiveAlert {
  id: string;
  type: AlertType;
  severity: "info" | "warning" | "critical";
  title: string;
  message: string;
  data: Record<string, unknown>;
  suggestedAction?: string;
  autoActionAvailable: boolean;
  detectedAt: number;
  acknowledgedAt?: number;
  resolvedAt?: number;
  status: "active" | "acknowledged" | "resolved" | "dismissed";
}

export type AlertType =
  | "anomaly"           // Unexpected metric change
  | "threshold"         // Metric crossed threshold
  | "trend"             // Emerging trend detected
  | "risk"              // Risk identified (churn, stockout, etc.)
  | "opportunity"       // Business opportunity detected
  | "reminder"          // Scheduled reminder
  | "completion"        // Autonomous task completed
  ;

// ─── Workflow Automation ────────────────────────────────────────────────────

export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  trigger: WorkflowTrigger;
  steps: WorkflowStep[];
  isActive: boolean;
  createdFrom: "natural_language" | "manual" | "ai_suggested";
  createdAt: number;
  lastRunAt?: number;
  runCount: number;
}

export interface WorkflowTrigger {
  type: "db_event" | "schedule" | "condition" | "manual" | "alert";
  config: Record<string, unknown>;  // e.g., { table: "orders", event: "insert" }
  description: string;
}

export interface WorkflowStep {
  id: number;
  agent: SubAgentType;
  action: string;
  params: Record<string, unknown>;
  condition?: string;               // Skip if condition is false
  delayMs?: number;                 // Wait before executing
  onFailure: "stop" | "skip" | "retry";
}

// ─── SSE Events for Autonomous System ───────────────────────────────────────

export type AutonomousSSEType =
  | "plan_created"
  | "phase_start"
  | "phase_complete"
  | "task_start"
  | "task_progress"
  | "task_complete"
  | "task_failed"
  | "content_generated"
  | "approval_needed"
  | "approval_resolved"
  | "alert_fired"
  | "workflow_triggered"
  | "agent_thinking"
  | "agent_delegating"
  | "quality_check"
  | "text"
  | "done"
  | "error"
  ;

export interface AutonomousSSEEvent {
  type: AutonomousSSEType;
  data: Record<string, unknown>;
  timestamp: number;
  planId?: string;
  taskId?: string;
  agent?: SubAgentType;
}
