import type { AtlasSurfaceContract } from "./types";

type SurfaceInput = Omit<AtlasSurfaceContract, "auditEnabled"> & {
  auditEnabled?: boolean;
};

function buildSurface(input: SurfaceInput): AtlasSurfaceContract {
  return {
    ...input,
    auditPath: input.auditPath ?? (input.route.includes("[") || input.route.includes("#") ? null : input.route),
    auditEnabled: input.auditEnabled ?? !input.route.includes("#"),
  };
}

function getAuditCustomerId() {
  return process.env.ATLAS_JARVIS_AUDIT_CUSTOMER_ID?.trim() || "6a3e8856-ef67-4ec1-a856-b92f53795ea1";
}

function getOptionalAuditPath(prefix: string, value: string | undefined) {
  const trimmed = value?.trim();
  return trimmed ? `${prefix}${trimmed}` : null;
}

const CUSTOMER_SURFACES: AtlasSurfaceContract[] = [
  buildSurface({
    id: "customer-dashboard",
    route: "/panel/dashboard",
    title: "Customer Dashboard",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_launch_overview",
    stateSource: "customer-workspace.dashboard",
    allowedEntryPoints: ["route:/panel/dashboard"],
    targetFiles: [
      "src/app/(client)/panel/dashboard/_components/dashboard-content.tsx",
      "src/components/portal/portal-page-hero.tsx",
    ],
    tags: ["customer", "launch", "hero", "overview"],
  }),
  buildSurface({
    id: "customer-process",
    route: "/panel/process",
    title: "Customer Process",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_process_tracking",
    stateSource: "customer-workspace.process",
    allowedEntryPoints: ["route:/panel/process"],
    targetFiles: [
      "src/app/(client)/panel/process/_components/process-content.tsx",
      "src/components/portal/observer-workstream-content.tsx",
    ],
    tags: ["customer", "timeline", "process"],
  }),
  buildSurface({
    id: "customer-services",
    route: "/panel/services",
    title: "Customer Services",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_services_control",
    stateSource: "customer-workspace.services",
    allowedEntryPoints: ["route:/panel/services"],
    targetFiles: [
      "src/app/(client)/panel/services/_components/services-content.tsx",
      "src/components/portal/request-hub-content.tsx",
    ],
    tags: ["customer", "services", "forms", "requests"],
  }),
  buildSurface({
    id: "customer-store",
    route: "/panel/store",
    title: "Customer Store",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_channel_selection",
    stateSource: "customer-workspace.store-experience",
    allowedEntryPoints: ["route:/panel/store"],
    targetFiles: [
      "src/app/(client)/panel/store/_components/store-content.tsx",
      "src/lib/customer-workspace/store-experience.ts",
    ],
    tags: ["customer", "store", "offers", "marketplace"],
  }),
  buildSurface({
    id: "customer-support",
    route: "/panel/support",
    title: "Customer Support",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_support_center",
    stateSource: "customer-portal.support-overview",
    allowedEntryPoints: ["route:/panel/support", "cta:module_unlock"],
    targetFiles: [
      "src/app/(client)/panel/support/_components/support-content.tsx",
      "src/components/portal/support-center-content.tsx",
    ],
    tags: ["customer", "support", "unlock", "context"],
  }),
  buildSurface({
    id: "customer-support-form",
    route: "/panel/support/forms/[code]",
    auditPath: getOptionalAuditPath("/panel/support/forms/", process.env.ATLAS_JARVIS_AUDIT_SUPPORT_FORM_CODE),
    auditEnabled: Boolean(process.env.ATLAS_JARVIS_AUDIT_SUPPORT_FORM_CODE?.trim()),
    title: "Customer Support Form",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_support_form",
    stateSource: "customer-support.form",
    allowedEntryPoints: ["route:/panel/support/forms/[code]"],
    targetFiles: [
      "src/app/(client)/panel/support/forms/[code]/page.tsx",
      "src/app/(client)/panel/support/forms/[code]/_components/form-fill-content.tsx",
    ],
    tags: ["customer", "support", "form", "dynamic"],
  }),
  buildSurface({
    id: "customer-support-submission",
    route: "/panel/support/submissions/[id]",
    auditPath: getOptionalAuditPath("/panel/support/submissions/", process.env.ATLAS_JARVIS_AUDIT_SUPPORT_SUBMISSION_ID),
    auditEnabled: Boolean(process.env.ATLAS_JARVIS_AUDIT_SUPPORT_SUBMISSION_ID?.trim()),
    title: "Customer Support Submission",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_support_submission",
    stateSource: "customer-support.submission",
    allowedEntryPoints: ["route:/panel/support/submissions/[id]"],
    targetFiles: [
      "src/app/(client)/panel/support/submissions/[id]/page.tsx",
    ],
    tags: ["customer", "support", "submission", "dynamic"],
  }),
  buildSurface({
    id: "customer-requests-page",
    route: "/panel/requests",
    title: "Customer Requests Page",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_requests_fullpage",
    stateSource: "customer-workspace.requestThreads",
    allowedEntryPoints: ["route:/panel/requests"],
    targetFiles: [
      "src/components/portal/request-hub-content.tsx",
      "src/app/(client)/panel/requests/page.tsx",
    ],
    tags: ["customer", "requests", "forms", "page"],
  }),
  buildSurface({
    id: "customer-requests-modal",
    route: "/panel/requests#modal",
    title: "Customer Requests Modal",
    owner: "customer",
    surfaceKind: "modal_safe",
    primaryJourney: "customer_requests_modal",
    stateSource: "customer-workspace.requestThreads",
    allowedEntryPoints: ["modal:requests-hub"],
    targetFiles: [
      "src/components/hub/customer-requests-hub-modal.tsx",
      "src/components/hub/workspace-modal-shell.tsx",
    ],
    tags: ["customer", "requests", "modal", "surface"],
    auditEnabled: false,
  }),
  buildSurface({
    id: "customer-companies",
    route: "/panel/companies",
    title: "Customer Companies",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_company_setup",
    stateSource: "customer-workspace.companies",
    allowedEntryPoints: ["route:/panel/companies"],
    targetFiles: ["src/app/(client)/panel/companies/page.tsx"],
    tags: ["customer", "company", "llc"],
  }),
  buildSurface({
    id: "customer-marketplaces",
    route: "/panel/marketplaces",
    title: "Customer Marketplaces",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_marketplace_operations",
    stateSource: "customer-workspace.marketplaces",
    allowedEntryPoints: ["route:/panel/marketplaces"],
    targetFiles: ["src/app/(client)/panel/marketplaces/page.tsx"],
    tags: ["customer", "marketplaces", "channels"],
  }),
  buildSurface({
    id: "customer-products",
    route: "/panel/products",
    title: "Customer Products",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_product_intake",
    stateSource: "customer-workspace.products",
    allowedEntryPoints: ["route:/panel/products"],
    targetFiles: ["src/app/(client)/panel/products/page.tsx"],
    tags: ["customer", "products", "catalog"],
  }),
  buildSurface({
    id: "customer-orders",
    route: "/panel/orders",
    title: "Customer Orders",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_orders_overview",
    stateSource: "customer-workspace.orders",
    allowedEntryPoints: ["route:/panel/orders"],
    targetFiles: ["src/app/(client)/panel/orders/page.tsx"],
    tags: ["customer", "orders", "operations"],
  }),
  buildSurface({
    id: "customer-order-detail",
    route: "/panel/orders/[id]",
    auditPath: getOptionalAuditPath("/panel/orders/", process.env.ATLAS_JARVIS_AUDIT_ORDER_ID),
    auditEnabled: Boolean(process.env.ATLAS_JARVIS_AUDIT_ORDER_ID?.trim()),
    title: "Customer Order Detail",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_order_detail",
    stateSource: "customer-workspace.order-detail",
    allowedEntryPoints: ["route:/panel/orders/[id]"],
    targetFiles: ["src/app/(client)/panel/orders/[id]/page.tsx"],
    tags: ["customer", "orders", "detail", "dynamic"],
  }),
  buildSurface({
    id: "customer-warehouse",
    route: "/panel/warehouse",
    title: "Customer Warehouse",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_warehouse_operations",
    stateSource: "customer-workspace.warehouse",
    allowedEntryPoints: ["route:/panel/warehouse"],
    targetFiles: ["src/app/(client)/panel/warehouse/page.tsx"],
    tags: ["customer", "warehouse", "fulfillment"],
  }),
  buildSurface({
    id: "customer-social-media",
    route: "/panel/social-media",
    title: "Customer Social Media",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_social_lane",
    stateSource: "customer-workspace.social-media",
    allowedEntryPoints: ["route:/panel/social-media"],
    targetFiles: ["src/app/(client)/panel/social-media/page.tsx"],
    tags: ["customer", "social", "growth"],
  }),
  buildSurface({
    id: "customer-advertising",
    route: "/panel/advertising",
    title: "Customer Advertising",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_advertising_lane",
    stateSource: "customer-workspace.advertising",
    allowedEntryPoints: ["route:/panel/advertising"],
    targetFiles: ["src/app/(client)/panel/advertising/page.tsx"],
    tags: ["customer", "ads", "growth"],
  }),
  buildSurface({
    id: "customer-finance",
    route: "/panel/finance",
    title: "Customer Finance",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_finance_lane",
    stateSource: "customer-workspace.finance",
    allowedEntryPoints: ["route:/panel/finance"],
    targetFiles: ["src/app/(client)/panel/finance/page.tsx"],
    tags: ["customer", "finance", "reports"],
  }),
  buildSurface({
    id: "customer-reports",
    route: "/panel/reports",
    title: "Customer Reports",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_reports_lane",
    stateSource: "customer-workspace.reports",
    allowedEntryPoints: ["route:/panel/reports"],
    targetFiles: ["src/app/(client)/panel/reports/page.tsx"],
    tags: ["customer", "reports", "analytics"],
  }),
  buildSurface({
    id: "customer-performance",
    route: "/panel/performance",
    title: "Customer Performance",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_performance_lane",
    stateSource: "customer-workspace.performance",
    allowedEntryPoints: ["route:/panel/performance"],
    targetFiles: ["src/app/(client)/panel/performance/page.tsx"],
    tags: ["customer", "performance", "analytics"],
  }),
  buildSurface({
    id: "customer-billing",
    route: "/panel/billing",
    title: "Customer Billing",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_billing_center",
    stateSource: "customer-workspace.billing",
    allowedEntryPoints: ["route:/panel/billing"],
    targetFiles: ["src/app/(client)/panel/billing/page.tsx"],
    tags: ["customer", "billing", "finance"],
  }),
  buildSurface({
    id: "customer-documents",
    route: "/panel/documents",
    title: "Customer Documents",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_documents_center",
    stateSource: "customer-workspace.documents",
    allowedEntryPoints: ["route:/panel/documents"],
    targetFiles: ["src/app/(client)/panel/documents/page.tsx"],
    tags: ["customer", "documents", "utility"],
  }),
  buildSurface({
    id: "customer-deliverables",
    route: "/panel/deliverables",
    title: "Customer Deliverables",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_deliverables_center",
    stateSource: "customer-workspace.deliverables",
    allowedEntryPoints: ["route:/panel/deliverables"],
    targetFiles: ["src/app/(client)/panel/deliverables/page.tsx"],
    tags: ["customer", "deliverables", "utility"],
  }),
  buildSurface({
    id: "customer-settings",
    route: "/panel/settings",
    title: "Customer Settings",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_settings",
    stateSource: "customer-settings",
    allowedEntryPoints: ["route:/panel/settings"],
    targetFiles: ["src/app/(client)/panel/settings/page.tsx"],
    tags: ["customer", "settings", "utility"],
  }),
  buildSurface({
    id: "customer-website",
    route: "/panel/website",
    title: "Customer Website",
    owner: "customer",
    surfaceKind: "page_only",
    primaryJourney: "customer_website_lane",
    stateSource: "customer-workspace.website",
    allowedEntryPoints: ["route:/panel/website"],
    targetFiles: ["src/app/(client)/panel/website/page.tsx"],
    tags: ["customer", "website", "launch"],
  }),
];

const ADMIN_SURFACES: AtlasSurfaceContract[] = [
  buildSurface({
    id: "admin-dashboard",
    route: "/admin/dashboard",
    title: "Admin Dashboard",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_operations_overview",
    stateSource: "admin.dashboard",
    allowedEntryPoints: ["route:/admin/dashboard"],
    targetFiles: ["src/app/(admin)/admin/dashboard/page.tsx"],
    tags: ["admin", "overview"],
  }),
  buildSurface({
    id: "admin-ai",
    route: "/admin/ai",
    title: "Admin AI Control Tower",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_ai_control_tower",
    stateSource: "admin.ai.control-tower",
    allowedEntryPoints: ["route:/admin/ai"],
    targetFiles: [
      "src/app/(admin)/admin/ai/page.tsx",
      "src/components/ai/atlas-copilot.tsx",
    ],
    tags: ["admin", "ai", "jarvis"],
  }),
  buildSurface({
    id: "admin-ai-operator",
    route: "/admin/ai/operator",
    title: "Admin AI Operator",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_ai_operator",
    stateSource: "admin.ai.operator",
    allowedEntryPoints: ["route:/admin/ai/operator"],
    targetFiles: ["src/app/(admin)/admin/ai/operator/page.tsx"],
    tags: ["admin", "ai", "operator"],
  }),
  buildSurface({
    id: "admin-customers",
    route: "/admin/customers",
    title: "Admin Customers",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_customers_index",
    stateSource: "admin.customers",
    allowedEntryPoints: ["route:/admin/customers"],
    targetFiles: ["src/app/(admin)/admin/customers/page.tsx"],
    tags: ["admin", "customers"],
  }),
  buildSurface({
    id: "admin-customer-detail",
    route: "/admin/customers/[id]",
    auditPath: `/admin/customers/${getAuditCustomerId()}`,
    title: "Admin Customer Detail",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_customer_detail",
    stateSource: "admin.customer-detail",
    allowedEntryPoints: ["route:/admin/customers/[id]"],
    targetFiles: ["src/app/(admin)/admin/customers/[id]/page.tsx"],
    tags: ["admin", "customers", "detail", "dynamic"],
  }),
  buildSurface({
    id: "admin-customer-workspace-modal",
    route: "/admin/customers/[id]#workspace",
    title: "Admin Customer Workspace Modal",
    owner: "admin",
    surfaceKind: "drawer_safe",
    primaryJourney: "admin_customer_workspace",
    stateSource: "customer-workspace.admin-panel",
    allowedEntryPoints: ["modal:admin-operations-hub"],
    targetFiles: [
      "src/app/(admin)/admin/customers/[id]/_components/admin-operations-hub-modal.tsx",
      "src/components/hub/workspace-modal-shell.tsx",
    ],
    tags: ["admin", "workspace", "modal"],
    auditEnabled: false,
  }),
  buildSurface({
    id: "admin-leads",
    route: "/admin/leads",
    title: "Admin Leads",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_leads",
    stateSource: "admin.leads",
    allowedEntryPoints: ["route:/admin/leads"],
    targetFiles: ["src/app/(admin)/admin/leads/page.tsx"],
    tags: ["admin", "crm", "leads"],
  }),
  buildSurface({
    id: "admin-companies",
    route: "/admin/companies",
    title: "Admin Companies",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_companies",
    stateSource: "admin.companies",
    allowedEntryPoints: ["route:/admin/companies"],
    targetFiles: ["src/app/(admin)/admin/companies/page.tsx"],
    tags: ["admin", "companies", "llc"],
  }),
  buildSurface({
    id: "admin-marketplaces",
    route: "/admin/marketplaces",
    title: "Admin Marketplaces",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_marketplaces",
    stateSource: "admin.marketplaces",
    allowedEntryPoints: ["route:/admin/marketplaces"],
    targetFiles: ["src/app/(admin)/admin/marketplaces/page.tsx"],
    tags: ["admin", "marketplaces"],
  }),
  buildSurface({
    id: "admin-social-media",
    route: "/admin/social-media",
    title: "Admin Social Media",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_social_media",
    stateSource: "admin.social-media",
    allowedEntryPoints: ["route:/admin/social-media"],
    targetFiles: ["src/app/(admin)/admin/social-media/page.tsx"],
    tags: ["admin", "social", "growth"],
  }),
  buildSurface({
    id: "admin-advertising",
    route: "/admin/advertising",
    title: "Admin Advertising",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_advertising",
    stateSource: "admin.advertising",
    allowedEntryPoints: ["route:/admin/advertising"],
    targetFiles: ["src/app/(admin)/admin/advertising/page.tsx"],
    tags: ["admin", "ads", "growth"],
  }),
  buildSurface({
    id: "admin-workflows",
    route: "/admin/workflows",
    title: "Admin Workflows",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_workflows",
    stateSource: "admin.workflows",
    allowedEntryPoints: ["route:/admin/workflows"],
    targetFiles: ["src/app/(admin)/admin/workflows/page.tsx"],
    tags: ["admin", "operations", "workflows"],
  }),
  buildSurface({
    id: "admin-inventory",
    route: "/admin/inventory",
    title: "Admin Inventory",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_inventory",
    stateSource: "admin.inventory",
    allowedEntryPoints: ["route:/admin/inventory"],
    targetFiles: ["src/app/(admin)/admin/inventory/page.tsx"],
    tags: ["admin", "inventory", "operations"],
  }),
  buildSurface({
    id: "admin-inventory-movement-modal",
    route: "/admin/inventory#movement-modal",
    title: "Admin Inventory Movement Modal",
    owner: "admin",
    surfaceKind: "modal_safe",
    primaryJourney: "admin_inventory_movement_modal",
    stateSource: "admin.inventory.modal",
    allowedEntryPoints: ["modal:inventory-movement"],
    targetFiles: [
      "src/app/(admin)/admin/inventory/page.tsx",
      "src/components/shared/modal-wrapper.tsx",
    ],
    tags: ["admin", "inventory", "modal"],
    auditEnabled: false,
  }),
  buildSurface({
    id: "admin-warehouse",
    route: "/admin/warehouse",
    title: "Admin Warehouse",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_warehouse",
    stateSource: "admin.warehouse",
    allowedEntryPoints: ["route:/admin/warehouse"],
    targetFiles: ["src/app/(admin)/admin/warehouse/page.tsx"],
    tags: ["admin", "warehouse", "operations"],
  }),
  buildSurface({
    id: "admin-orders",
    route: "/admin/orders",
    title: "Admin Orders",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_orders",
    stateSource: "admin.orders",
    allowedEntryPoints: ["route:/admin/orders"],
    targetFiles: ["src/app/(admin)/admin/orders/page.tsx"],
    tags: ["admin", "orders", "operations"],
  }),
  buildSurface({
    id: "admin-documents",
    route: "/admin/documents",
    title: "Admin Documents",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_documents",
    stateSource: "admin.documents",
    allowedEntryPoints: ["route:/admin/documents"],
    targetFiles: ["src/app/(admin)/admin/documents/page.tsx"],
    tags: ["admin", "documents", "utility"],
  }),
  buildSurface({
    id: "admin-forms",
    route: "/admin/forms",
    title: "Admin Forms",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_forms",
    stateSource: "admin.forms",
    allowedEntryPoints: ["route:/admin/forms"],
    targetFiles: ["src/app/(admin)/admin/forms/page.tsx"],
    tags: ["admin", "forms", "utility"],
  }),
  buildSurface({
    id: "admin-forms-detail-modal",
    route: "/admin/forms#detail-modal",
    title: "Admin Forms Detail Modal",
    owner: "admin",
    surfaceKind: "modal_safe",
    primaryJourney: "admin_forms_detail_modal",
    stateSource: "admin.forms.modal",
    allowedEntryPoints: ["modal:forms-detail"],
    targetFiles: [
      "src/app/(admin)/admin/forms/page.tsx",
      "src/components/shared/modal-wrapper.tsx",
    ],
    tags: ["admin", "forms", "modal"],
    auditEnabled: false,
  }),
  buildSurface({
    id: "admin-finance",
    route: "/admin/finance",
    title: "Admin Finance",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_finance",
    stateSource: "admin.finance",
    allowedEntryPoints: ["route:/admin/finance"],
    targetFiles: ["src/app/(admin)/admin/finance/page.tsx"],
    tags: ["admin", "finance", "operations"],
  }),
  buildSurface({
    id: "admin-billing",
    route: "/admin/billing",
    title: "Admin Billing",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_billing",
    stateSource: "admin.billing",
    allowedEntryPoints: ["route:/admin/billing"],
    targetFiles: ["src/app/(admin)/admin/billing/page.tsx"],
    tags: ["admin", "billing", "finance"],
  }),
  buildSurface({
    id: "admin-support",
    route: "/admin/support",
    title: "Admin Support",
    owner: "admin",
    surfaceKind: "page_only",
    primaryJourney: "admin_support_operations",
    stateSource: "support.admin",
    allowedEntryPoints: ["route:/admin/support"],
    targetFiles: ["src/app/(admin)/admin/support/page.tsx"],
    tags: ["admin", "support", "operations"],
  }),
  buildSurface({
    id: "admin-support-reply-modal",
    route: "/admin/support#reply-modal",
    title: "Admin Support Reply Modal",
    owner: "admin",
    surfaceKind: "modal_safe",
    primaryJourney: "admin_support_reply_modal",
    stateSource: "support.admin.modal",
    allowedEntryPoints: ["modal:support-reply"],
    targetFiles: [
      "src/app/(admin)/admin/support/page.tsx",
      "src/components/shared/modal-wrapper.tsx",
    ],
    tags: ["admin", "support", "modal"],
    auditEnabled: false,
  }),
];

const MARKETING_SURFACES: AtlasSurfaceContract[] = [
  buildSurface({
    id: "marketing-home",
    route: "/",
    title: "Marketing Home",
    owner: "marketing",
    surfaceKind: "page_only",
    primaryJourney: "public_homepage",
    stateSource: "marketing.home",
    allowedEntryPoints: ["route:/"],
    targetFiles: ["src/app/(marketing)/page.tsx"],
    tags: ["public", "marketing", "hero"],
  }),
  buildSurface({
    id: "marketing-pricing",
    route: "/pricing",
    title: "Marketing Pricing",
    owner: "marketing",
    surfaceKind: "page_only",
    primaryJourney: "public_pricing",
    stateSource: "marketing.pricing",
    allowedEntryPoints: ["route:/pricing"],
    targetFiles: ["src/app/(marketing)/pricing/page.tsx"],
    tags: ["public", "pricing"],
  }),
  buildSurface({
    id: "marketing-contact",
    route: "/contact",
    title: "Marketing Contact",
    owner: "marketing",
    surfaceKind: "page_only",
    primaryJourney: "public_application",
    stateSource: "marketing.contact",
    allowedEntryPoints: ["route:/contact"],
    targetFiles: ["src/app/(marketing)/contact/page.tsx"],
    tags: ["public", "application", "contact"],
  }),
  buildSurface({
    id: "marketing-about",
    route: "/about",
    title: "Marketing About",
    owner: "marketing",
    surfaceKind: "page_only",
    primaryJourney: "public_about",
    stateSource: "marketing.about",
    allowedEntryPoints: ["route:/about"],
    targetFiles: ["src/app/(marketing)/about/page.tsx"],
    tags: ["public", "about"],
  }),
];

const AUTH_SURFACES: AtlasSurfaceContract[] = [
  buildSurface({
    id: "customer-login",
    route: "/login",
    title: "Customer Login",
    owner: "shared",
    surfaceKind: "page_only",
    primaryJourney: "customer_auth_login",
    stateSource: "auth.customer.login",
    allowedEntryPoints: ["route:/login"],
    targetFiles: ["src/app/(auth)/login/page.tsx"],
    tags: ["auth", "customer", "login"],
  }),
  buildSurface({
    id: "admin-login",
    route: "/admin/login",
    title: "Admin Login",
    owner: "shared",
    surfaceKind: "page_only",
    primaryJourney: "admin_auth_login",
    stateSource: "auth.admin.login",
    allowedEntryPoints: ["route:/admin/login"],
    targetFiles: ["src/app/(admin-auth)/admin/login/page.tsx"],
    tags: ["auth", "admin", "login"],
  }),
];

export const ATLAS_SURFACE_REGISTRY: AtlasSurfaceContract[] = [
  ...CUSTOMER_SURFACES,
  ...ADMIN_SURFACES,
  ...MARKETING_SURFACES,
  ...AUTH_SURFACES,
];

export function listAtlasSurfaces() {
  return ATLAS_SURFACE_REGISTRY;
}

export function listAtlasAuditableSurfaces() {
  return ATLAS_SURFACE_REGISTRY.filter((surface) => surface.auditEnabled !== false && surface.auditPath);
}

export function getAtlasSurfaceByRoute(route: string) {
  return ATLAS_SURFACE_REGISTRY.find((surface) => surface.route === route || surface.auditPath === route) ?? null;
}

export function getAtlasJourneyRoutes() {
  return Array.from(new Set(listAtlasAuditableSurfaces().map((surface) => surface.auditPath!)));
}
